version: '3.7'
volumes:
  node_modules:
services:
  postgres:
    image: postgres:10.1-alpine
    ports:
      - '5432:5432'
    # environment:
    #   POSTGRES_DB: schools-out
  # redis:
  #   image: redis:4.0.2-alpine
  #   ports:
  #     - '6379:6379'
  web:
    image: schools-out-api/web
    build:
      context: .
    command: 'yarn dev'
    ports:
      - '4060:4060'
      - '3000:3000'
      # - '9229:9229'
    depends_on:
      - postgres
      # - redis

  dev:
    image: schools-out-api/dev
    environment:
      POSTGRES_DB: schools-out
    env_file: env-dist.env
    build:
      context: .
    command: ['npm', 'rebuild', 'update-binary']
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    ports:
      - '4060:4060'
      - '3000:3000'
      - '9229:9229'
    depends_on:
      - postgres
      # - redis
